### ISSUE TITLE
Code de Nexecur-Unofficial-API

### ISSUE THREAD

**Issue by Chuckame** [quelqundev/NexecureScheduler#26]
Hello,

Aurais-tu quelque part le code de [https://github.com/baudev/Nexecur-Unofficial-API 33](https://github.com/baudev/Nexecur-Unofficial-API) ? Il est maintenant, et je souhaiterais faire une intégration pour home assistant.

**Comment by baudev** [comment]
Salut, 

Je n'ai pas bien compris la question... "Il est maintenant" quoi ?

**Comment by Chuckame** [comment]
Il est maintenant indisponible, désolé !

Aurais tu le code qui traîne dans un coin ?

**Comment by Chuckame** [comment]
Après pas mal de bidouille, j'ai réussi à faire quelque chose, merci quand même 😄
